### ISSUE TITLE
Property name typo

### ISSUE THREAD

**Issue by SaekiTominaga** [Pigotz/paapi5-typescript-sdk#3]
Hi, After installing this package, I get a TS2551 error when processing `GetItems`.
I think `ItemsResult` is correct for `ItemResults` below.
https://github.com/Pigotz/paapi5-typescript-sdk/blob/develop/src/requests/GetItemsRequest.ts#L46

**Comment by Pigotz** [comment]
Hi @SaekiTominaga :wave: 

Sounds strange though, the code is aligned with the [documentation](https://webservices.amazon.com/paapi5/documentation/get-items.html#ItemLookup-sr).

Is it possible that Amazon's documentation contains a typo as well?

Also, could you provide some example code? :pray:

**Comment by SaekiTominaga** [comment]
Thank you for your reply.
Indeed, the documentation says `ItemResults`. 🤔
However, in the [SDK](https://webservices.amazon.com/paapi5/documentation/quick-start/using-sdk.html) programs for Node.js (src/model/GetItemsResponse.js, src/model/ItemsResult.js), it is `ItemsResult`.

I've placed the actual code I tried in my repository.
- [repository](https://github.com/SaekiTominaga/paapi5-typescript-sdk-itemsresult-test)
- [index.ts](https://github.com/SaekiTominaga/paapi5-typescript-sdk-itemsresult-test/blob/main/index.ts)

This program will not work unless you set up an access key or secret key, so I am attaching a screenshot of it working.
![paapi5-typescript-sdk-itemsresult-test](https://user-images.githubusercontent.com/4138486/106551676-18f2eb80-6559-11eb-873d-65522041c185.png)

**Comment by Pigotz** [comment]
Hi @SaekiTominaga :wave: 

I've made a PR for this issue: https://github.com/Pigotz/paapi5-typescript-sdk/pull/4

Could you try it somehow?

**Comment by SaekiTominaga** [comment]
Thanks for the fix.
I've confirmed that the error on the editor has disappeared!
(And of course the data is retrieved correctly from the API.)
